### ISSUE TITLE
v1.8.8 doesn't forward requests to proxied server

### ISSUE THREAD

**Issue by llamahunter** [keattang/eks-auth-proxy#15]
I updated from a much older version to v1.8.8, and now it does not appear that eks-auth-proxy forwards requests to the proxied server anymore. It does authenticated with the backend oidc provider, and fetches the eks auth token.  But then it never makes a request with that information to the backend server. Downgraded eks-auth-proxy and it worked again. Something is up.

There's nothing useful in the --debug output to indicate why it's hanging.  The last lines printed (with stuff omitted):

```
debug:   Calling aws-iam-authenticator with
        clusterName=...elided...
        AWS_ACCESS_KEY_ID=...elided...
        AWS_SECRET_ACCESS_KEY=...elided...
        AWS_SESSION_TOKEN=...elided...
debug:   Upstream request headers: {"x-forwarded-host":"...elided...","x-forwarded-proto":"http","x-forwarded-port":"80","x-forwarded-for":"::ffff:...elided...","sec-gpc":"1","cookie":"koa.sess=...elided...; koa.sess.sig=...elided...","accept-language":"en-US,en;q=0.9","accept-encoding":"gzip, deflate","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","upgrade-insecure-requests":"1","dnt":"1","connection":"close","host":"kubernetes-dashboard:443","authorization":"Bearer k8s-aws-v1....elided..."}```

**Comment by keattang** [comment]
Hi @llamahunter sorry to hear you're having trouble. I'm not sure why it's not proxying as I have been using `v1.8.8` in production for some time now. I've just released a new version (`v1.9.0`), which also works on my end. Would you mind trying that and see if you're still having issues?

**Comment by llamahunter** [comment]
So, updated to the new 2.0.0 release, hoping to work around both this and the jwks_url issue. It is able to (now more reliably) authenticate with the oidc backend without getting the jwks_url error, but still does not forward requests to the backend server. Same behavior as reported here. Debug logs show it authenticates, prints the bearer token. I have even used that printed bearer token to manually connect to the backend server, so it's definitely accepted. Unclear why this does not work, and there's no additional info in the debug log. It just hangs.

(private things switched to xxx)

```
2022-08-30T00:42:51: PM2 log: Launching in no daemon mode
2022-08-30T00:42:51: PM2 log: App [index:0] starting in -fork mode-
2022-08-30T00:42:51: PM2 log: App [index:0] online
info:    Proxying requests to http://kubernetes-dashboard:443
info:    Proxy server running on port 3001
debug:   Assuming role arn:aws:iam::xxx:role/xxx-kubernetes-dashboard with sessionName xxx and token xxx
debug:   Calling aws-iam-authenticator with
        clusterName=xxx
        AWS_ACCESS_KEY_ID=xxx
        AWS_SECRET_ACCESS_KEY=xxx
        AWS_SESSION_TOKEN=xxx
debug:   Upstream request headers: {"x-forwarded-host":"dashboard.xxx.net","x-forwarded-proto":"http","x-forwarded-port":"80","x-forwarded-for":"::ffff:10.191.129.140","sec-gpc":"1","cookie":"koa.sess=xxx=; koa.sess.sig=xxx","accept-language":"en-US,en;q=0.9","accept-encoding":"gzip, deflate","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","upgrade-insecure-requests":"1","dnt":"1","cache-control":"max-age=0","connection":"close","host":"kubernetes-dashboard:443","authorization":"Bearer k8s-aws-v1.xxx"}
```

**Comment by keattang** [comment]
That's very odd. It's possibly something to do with the fact that you're targeting 443 on the kubernetes-dashboard pod. Does it work on an insecure port? This proxy assumes that you have terminated TLS before you get to it and that it can talk to the dashboard pod on an insecure port. 

I typically use it as a container in the same pod as the dashboard and then only expose the proxy outside the pod.

**Comment by llamahunter** [comment]
Due to 'weirdness' with the way the kubernetes dashboard works, it runs http on port 443.  Note that the url for the backend is http://kubernetes-dashboard:443. It's not https.  Also, that part of the config is unchanged. All I did was update to the newer version of eks-auth-proxy w/o changing anything else. It's odd that there's zero logging from eks-auth-proxy after it gets the bearer token. It's as though it's hanging on connect to the backend.

I can try changing the http port to 80, in case there something in newer versions of eks-auth-proxy which is ignoring the scheme and trying to use https anyway.

**Comment by llamahunter** [comment]
I updated to deploy the kubernetes-dashboard on port 80, and even tried listing both the service name and namespace (e.g. http://kubernetes-dashboard.kubernetes-dashboard:80), but it's exactly the same behavior. eks-auth-proxy just hangs after authenticating with oidc, and fetching the bearer token from aws-iam-authenticator.

**Comment by keattang** [comment]
Ah ok interesting. Could you please also try using the container inside the pod just to help narrow down potential sources of the issue?

Something like this:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kubernetes-dashboard
          image: kubernetesui/dashboard:v2.6.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              protocol: TCP
          args:
            - --namespace=kube-system
            - --enable-insecure-login
            # - --auto-generate-certificates
            # Uncomment the following line to manually specify Kubernetes API server Host
            # If not specified, Dashboard will attempt to auto discover the API server and connect
            # to it. Uncomment only if the default does not work.
            # - --apiserver-host=http://my-address:port
          volumeMounts:
            - name: kubernetes-dashboard-certs
              mountPath: /certs
              # Create on-disk volume to store exec logs
            - mountPath: /tmp
              name: tmp-volume
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
        - image: keattang/eks-auth-proxy:v1.9.0
          name: eks-auth-proxy
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: 700Mi
            requests:
              cpu: 50m
              memory: 700Mi
          command:
            - ./start
          args:
            - --proxy-host=localhost:9090
            - --proxy-preserve-host
            ...
      volumes:
        - name: kubernetes-dashboard-certs
          secret:
            secretName: kubernetes-dashboard-certs
        - name: tmp-volume
          emptyDir: {}
      serviceAccountName: kubernetes-dashboard
      nodeSelector:
        "kubernetes.io/os": linux
      # Comment the following tolerations if Dashboard must not be deployed on
      # master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
```
